services:
  openttd-server:
    image: ghcr.io/ropenttd/openttd:latest
    container_name: openttd-server-${INSTANCE_NAME}
    ports:
      - "${GAME_PORT}:${GAME_PORT}/tcp"
      - "${GAME_PORT}:${GAME_PORT}/udp"
    volumes:
      - ./openttd-cfg:/config
    restart: unless-stopped

  openttd-bot:
    build: 
      context: ./bot
    container_name: openttd-bot-${INSTANCE_NAME}
    depends_on:
      - openttd-server
    restart: unless-stopped